# Generated by Django 4.1 on 2022-12-13 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmeticapp', '0002_cartlist_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartlist',
            old_name='cart_Id',
            new_name='cart_id',
        ),
    ]
